"""A setuptools based setup module.

- Do not edit this file!!

- Edit `setup.cfg`, c.f. 
  https://setuptools.readthedocs.io/en/latest/setuptools.html#setup-cfg-only-projects
"""

from setuptools import setup
setup()  # Edit setup.cfg
